---
# handlers file for otn.hass.ar

- name: Restart Hass
  listen: Restart Hass
  become: yes
  service:
    name: hass
    state: restarted

- name: Wait for successful restart
  listen: Restart Hass
  wait_for:
    port: 8123
    delay: 10

    
- name: Reload Components
  listen: Reload Hass
  uri:
    url: http://localhost:8123/api/services/{{ item }}/reload
    method: POST
    headers:
      Authorization: Bearer {{ hass.api.key }}
      Content-Type: application/json
  with_items:
    - group
    - script
    - automation


