---

- name: Copy /etc template files 
  ansible.builtin.template:
    src: "{{ system_ar_otternet_conf_repo.local_folder }}/etc/{{ item.src }}"
    dest: /etc/{{ item.dst }}
    backup: yes
  become: yes
  with_items:
    - src: sudoers.d/all/ansible_user
      dst: sudoers.d/{{ ansible_user }}
  when: (system_ar_otternet_conf_repo.local_folder + '/etc/' + item.src) is exists

- name: Set authorized ci key
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', system_ar_otternet_conf_repo.local_folder + '/ssh/.ssh/id_rsa.pub') }}"