

- name: Copy restart configuration files
  copy:
    src: /tmp/hass-deployment/config/{{ zone_id }}/{{ item }}
    dest: /home/{{ ansible_user }}/homeass/config/
    remote_src: yes
    backup: yes
  with_items:
    - configuration.yaml
  notify: Restart Hass

- name: Copy reload configuration files 
  copy:
    src: /tmp/hass-deployment/config/{{ zone_id }}/{{ item }}
    dest: /home/{{ ansible_user }}/homeass/config/
    remote_src: yes
    backup: yes
  with_items:
    - automations.yaml
    - groups.yaml
  notify: Reload Hass

- name: Copy Common Files
  copy:
    src: /tmp/hass-deployment/config/common/{{ item.src }}
    dest: /home/{{ ansible_user }}/homeass/config/{{ item.dest }}
    remote_src: yes
    backup: yes
  with_items:
    - src: secrets.vault
      dest: secrets.vault
  notify: Restart Hass

#copy does not decrypt remote copy vault files...
- name: Create Ansible Vault Password File
  copy:
    content: "{{ ansible.vault.password }}"
    dest: /home/{{ ansible_user }}/vault-pw

- name: Decrypt Home Assistant secrets file(s)
  shell: ansible-vault decrypt /home/{{ ansible_user }}/homeass/config/{{ item.src }} --vault-password-file=/home/{{ ansible_user }}/vault-pw --output=/home/{{ ansible_user }}/homeass/config/{{ item.dest }}
  with_items:
    - src: secrets.vault
      dest: secrets.yaml