

- name: Copy restart configuration files
  copy:
    src: "{{ hass_ar_otternet_conf_repo.local_folder }}/hass/{{ inventory_hostname }}/{{ item }}"
    dest: /home/{{ ansible_user }}/homeass/config/
    remote_src: yes
    backup: yes
  with_items:
    - configuration.yaml
  notify: Restart Hass

- name: Copy reload configuration files 
  copy:
    src: "{{ hass_ar_otternet_conf_repo.local_folder }}/hass/{{ inventory_hostname }}/{{ item }}"
    dest: /home/{{ ansible_user }}/homeass/config/
    remote_src: yes
    backup: yes
  with_items:
    - automations
    - automations.yaml
    - groups.yaml
    - scripts.yaml
  notify: Reload Hass

- name: Copy Common Files
  copy:
    src: "{{ hass_ar_otternet_conf_repo.local_folder }}/hass/all/{{ item.src }}"
    dest: /home/{{ ansible_user }}/homeass/config/{{ item.dest }}
    remote_src: yes
    backup: yes
    decrypt: yes
  with_items:
    - src: secrets.vault
      dest: secrets.yaml
  notify: Restart Hass