---

- name: Add Home Assistant systemd service file
  ansible.builtin.copy:
    src: "{{ hass_ar_otternet_conf_repo.local_folder }}/systemd/{{ inventory_hostname }}/{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    backup: yes
  with_items:
    - otn.hass.service
  notify: Restart Hass

- name: Reload service(s)
  ansible.builtin.service:
    name: otn.hass.service
    enabled: yes
    state: reloaded
  notify: Restart Hass
  