---

- name: Add Home Assistant systemd service file
  ansible.builtin.template:
    src: "{{ hass_ar_otternet_conf_repo.local_folder }}/systemd/{{ inventory_hostname }}/{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    backup: yes
  register: hass_services
  with_items:
    - otn.hass.service
  notify: Restart Hass
  become: yes

- name: Restart affected service(s)
  ansible.builtin.systemd:
    name: "{{ item.item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes
  when: item.changed
  with_items: "{{ hass_services.results }}"
  